<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_BRANCH')); 
?>
<?php  $frm = $this->frm_term;?>
<form action="<?php echo $this->url(array('module'=>'other','controller'=>'term','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="10" style="margin: 0 auto; width:80%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("TERMCONDICTION");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%" cellspacing="10"  > 
								<tr>
										<td width="10%"><?php echo $tr->translate("CONDICTION_KH")?></td>
										<td width="90%">
											<textarea class="fullside" style=" width:100%; height:180px;" tabindex="" class="fullside" id="con_khmer" name="con_khmer"><?php echo $this->term['con_khmer'];?></textarea>
										</td>
									</tr>
									<tr>
									
										<td><?php echo $tr->translate("CONDICTION_EN")?></td>
										<td>
											<textarea class="fullside" style=" width:100%; height:180px;  tabindex="" class="fullside" id="con_english" name="con_english"><?php echo $this->term['con_english'];?></textarea>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("PAYMENT_TYPE")?></td>
										<td>
											<select name="payment_type" id="payment_type" dojoType="dijit.form.FilteringSelect" class="fullside" >
												<option value="0" > Select </option>
												<option value="1" <?php if($this->term['payment_type']==1){echo 'selected="selected"';}?> >បង់រំលោះ</option>
												<option value="2" <?php if($this->term['payment_type']==2){echo 'selected="selected"';}?> >បង់ដំណាក់កាល</option>
												<option value="3" <?php if($this->term['payment_type']==3){echo 'selected="selected"';}?> >បង់ផ្តាច់</option>
											</select>
										</td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("STATUS")?></td>
										<td><?php echo $frm->getElement("status");?></td>
									</tr>
									<tr>
										<td colspan="6" align="center">
											<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" />
											<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>