 <?php 
 $tr = Application_Form_FrmLanguages::getCurrentlanguage();
 ?>
 <?php 
	$tr= Application_Form_FrmLanguages::getCurrentlanguage();
	$rpt_client = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-client'));
	$rpt_callteral = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral'));
	$rpt_change_call = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-calleteral-change'));
	$rpt_return_call = $this->url(array('module'=>'report','controller'=>'groupmember','action'=>'rpt-returncollteral'));
	$rpt_property = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-properties'));
	$rpt_cancel = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-cancel-sale'));
	$rpt_expense = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-expense'));
	$rpt_income = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-income'));
	$rpt_daily_cash = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-daily-cash'));
	$rpt_sale_history = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-sale-history'));
?>
  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
 <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
  		<li><a href="<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-holiday')); ?>"><?php echo $tr->translate('LIST_HOLIDAY');?></a></li>
  		<li><a href="<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-staff')); ?>"><?php echo $tr->translate('LIST_STAFF');?></a></li>
  		<li><a href="<?php echo $this->url(array('module'=>'report','controller'=>'Paramater','action'=>'rpt-village')); ?>"><?php echo $tr->translate('LIST_VILLAGE');?></a></li>
  		<li><a href="<?php echo $rpt_client;?>"><?php echo $tr->translate('LIST_OF_CLIENT');?></a></li>
  		<li><a href="<?php echo $rpt_property;?>"><?php echo $tr->translate('LIST_PROPERTY');?></a></li>
  		<li><a href="<?php echo $rpt_cancel;?>"><?php echo $tr->translate('CANCEL_REPORT');?></a></li>
  		<li><a href="<?php echo $rpt_income;?>"><?php echo $tr->translate('REPORT_INCOME');?></a></li>
  		<li><a href="<?php echo $rpt_expense;?>"><?php echo $tr->translate('REPORT_EXPENSE');?></a></li>
  		<li><a href="<?php echo $rpt_daily_cash;?>"><?php echo $tr->translate('REPORT_DAILY_CASH');?></a></li>
  		<li><a href="<?php echo $rpt_sale_history;?>"><?php echo $tr->translate('REPORT_SALE_HISTORY');?></a></li>
  	</ul>
</div>