<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_cancel;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("CANCEL_SALE_REPORT");?></title>
<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-cancel-sale')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:28cm; margin: 0 auto;">
		 <tr>
			<td><?php echo $frm->getElement('adv_search');?></td>
			<td><?php echo $frm->getElement('branch_id_search');?></td>
			<td><?php echo $frm->getElement('property_type');?></td>
			<td><?php echo $frm->getElement('from_date_search');?></td>
			<td><?php echo $frm->getElement('to_date_search');?></td>
			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		</tr>
	</table>
 </form> 
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
    	 	<style>
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Khmer OS Battambang';
						}
						th{padding: 5px;}
					</style>
        	<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
        	<tr>
                <td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                <td width="60%" valign="top">
                <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRAND_TITLE");?></label></h2>
                <h2 style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("CANCEL_SALE_REPORT");?></label></h2>
                <td width="20%"></td>
             </tr> 
            <tr>
            	<td colspan="3">
            		<table id="exportExcel" width="100%" style="border-collapse:collapse;font-size: 14px;" >  
				    	
				       <?php $property_type=''; $i=0; $total=0; if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
				      	<?php  
						if($row['property_type']!=$property_type){	
							if($key>0 ){
						?>
														
							<?php $i=1;}?>
					</table>
						</td>
					</tr>
					<tr><td></td></tr>
					<tr><td></td></tr>
					<tr><td></td></tr>
					<tr>
						<td colspan="3">
							<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size: 14px;  line-height: 24px;" bordercolor="black">
								<tr style=" border-top: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
									<td colspan="7"><strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2'; padding:5px;" ><?php echo $row['type_name']; ?></strong></td>
								</tr>
								<tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; line-height: 24px; font-size:14px; padding:5px 0px; " >
									<th ><?php echo $tr->translate("NUM");?></th>
									      <th><?php echo $tr->translate("SALE_NO");?></th>
									      <th><?php echo $tr->translate("CLIENT_NO");?></th>
									      <th><?php echo $tr->translate("CLIENT_NAME");?></th>
									      <th><?php echo $tr->translate("PROJECT_NAME");?></th>
									      <th><?php echo $tr->translate("PROPERY_CODE");?></th>
									      <th><?php echo $tr->translate("PROPERTY_NAME");?></th>
									      <th><?php echo $tr->translate("STREET");?></th>
									      <th><?php echo $tr->translate("PROPERTY_TYPE");?></th>
									      <th><?php echo $tr->translate("DATE");?></th>
									</tr>
						<?php }
						$property_type= $row['property_type'];
						?>
						   <tr style="font-size: 12px;" align="left">
						     <td align="center">&nbsp;<?php echo $i; ?></td>
						     <td align="center">&nbsp;<?php echo $row['sale_number'];?></td>
						     <td align="center">&nbsp;<?php echo $row['client_number'];?></td>
							 <td align="center">&nbsp;<?php echo $row['client_name'];?></td>
							 <td>&nbsp;<?php echo $row['project_name'];?></td>
							 <td align="center">&nbsp;<?php echo $row['land_code'];?></td>
							  <td align="center">&nbsp;<?php echo $row['land_address'];?></td>
							   <td align="center">&nbsp;<?php echo $row['street'];?></td>
							 <td align="center">&nbsp;<?php echo $row['type_name'];?></td>
							 <td align="center">&nbsp;<?php echo date("d-M-Y",strtotime($row['create_date']));?></td>
							</tr>
						<?php }?>
				    </table>
            	</td>
            </tr>
            </table>
			
    	</td>
    </tr>
</table>
		<br />
		   <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
</div>
