<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_property;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_PROPERTY");?></title>
<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-properties')); ?>" dojoType="dijit.form.Form" method="post">
	<table style="width:28cm; margin: 0 auto;">
		 <tr> 
			   <td><?php echo $frm->getElement("adv_search");?></td>
			   <td><?php echo $frm->getElement("branch_id");?></td>
			   <td><?php echo $frm->getElement("property_type");?></td>
			   <td><?php echo $frm->getElement("type_property_sale");?></td>
				<td>
			   <button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
			   </td>
	   	  </tr>
	   	  <tr>
		   	  <td><?php echo $frm->getElement('start_date');?></td>
		      <td><?php echo $frm->getElement('end_date');?></td>
		   </tr>
	</table>
 </form> 
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
    	 	<style>
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Khmer OS Battambang';
						}
						th{padding: 5px;}
table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
					</style>
        	<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
        	<tr>
                    <td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
                	<td width="60%" valign="top">
                		<ul>
                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BRAND_TITLE");?></li>
                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("TABLE_PROPERTY");?></li>
                			<li style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
                		</ul>
                	</td>
                    <td width="20%"></td>
            </tr> 
            <tr>
            	<td colspan="3">
            		<table id="exportExcel" width="100%" style="border-collapse:collapse;font-size: 14px;" >  
				    	
				       <?php $total_land_pric=0; $total_house_price = 0; $property_type=''; $i=0; $total=0; if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
				      	<?php  
						if($row['property_type']!=$property_type){	
							if($key>0 ){
						?>
						<tr style=" border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;"><td colspan="11">&nbsp;</td></tr>
							<tr style=" border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
								<td colspan="12">
									<table border="1"​ style="border-collapse:collapse; border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
						                 <tr bgcolor="#c1d0f3" class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                 	<td>&nbsp;<?php echo $tr->translate("TOTAL_PROPERTY");?>&nbsp;</td>
						                 	<td>&nbsp;<?php echo $tr->translate("TOTAL_LAND_PRICE");?>&nbsp;</td>
						                 	<td>&nbsp;<?php echo $tr->translate("TOTAL_HOUSE_PRICE");?>&nbsp;</td>
						                 	<td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
						                 </tr>
						                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
						                  	<td align="center">&nbsp;<?php echo $i;?></td>
						                    <td>&nbsp;&nbsp;<?php echo number_format($total_land_pric,2);?>&nbsp;</td>
						                    <td>&nbsp;&nbsp;<?php echo number_format($total_house_price,2);?>&nbsp;</td>
						                    <td>&nbsp;&nbsp;<?php echo number_format($total,2);?>&nbsp;</td>
						                </tr>
						              </table>
								</td>
							</tr>
							
							<?php $i=1;}?>
					</table>
						</td>
					</tr>
					<tr><td></td></tr>
					<tr><td></td></tr>
					<tr><td></td></tr>
					<tr>
						<td colspan="3">
							<table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size: 14px;     line-height: 24px;" bordercolor="black">
								<tr style=" border-top: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
									<td colspan="7"><strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2'; padding:5px;" ><?php echo $row['pro_type']; ?></strong></td>
								</tr>
								<tr bgcolor="#c1d0f3" class="style" align="center" style="floafont-weight:bold; line-height: 14px; line-height: 24px; font-size:14px; padding:5px 0px; " >
									<th ><?php echo $tr->translate("NUM");?></th>
									      <th><?php echo $tr->translate("PROPERTY_CODE");?></th>
									      <th><?php echo $tr->translate("HOUSE_NO");?></th>
									      <th><?php echo $tr->translate("STREET");?></th>
									      <th><?php echo $tr->translate("PROPERTY_TYPE");?></th>
									      <th><?php echo $tr->translate("SIZE");?></th>
									      <th><?php echo $tr->translate("WIDTH");?></th>
									      <th><?php echo $tr->translate("HEIGHT");?></th>
									      <th><?php echo $tr->translate("LAND_PRICE");?></th>
									      <th><?php echo $tr->translate("HOUSE_PRICE");?></th>
									      <th><?php echo $tr->translate("PRICE");?></th>
									      <th><?php echo $tr->translate("STATUS");?></th>
									</tr>
						<?php }?>
						   <tr style="font-size: 12px;" align="left">
						     <td align="center">&nbsp;<?php echo $i; ?></td>
						     <td align="center">&nbsp;<?php echo $row['land_code'];?>&nbsp;</td>
						     <td align="center">&nbsp;<?php echo $row['land_address'];?>&nbsp;</td>
							 <td align="center">&nbsp;<?php echo $row['street'];?>&nbsp;</td>
							 <td>&nbsp;<?php echo $row['pro_type'];?></td>
							 <td align="center">&nbsp;<?php echo $row['land_size'];?>&nbsp;</td>
							 <td align="center">&nbsp;<?php echo $row['width'];?>&nbsp;</td>
							 <td align="center">&nbsp;<?php echo $row['height'];?>&nbsp;</td>
							 <td align="right">&nbsp;<?php echo number_format($row['land_price'],2);?>&nbsp;</td>
							 <td align="right">&nbsp;<?php echo number_format($row['house_price'],2);?>&nbsp;</td>
							 <td align="right">&nbsp;<?php echo number_format($row['price'],2);?>&nbsp;</td>
							 <td align="center">&nbsp;<?php if ($row['is_lock']==1){ echo $tr->translate("SOLD_OUT");}else{ echo $tr->translate("NOT_YET_SALE"); }?>&nbsp;</td>
							</tr>
							<?php $total = $total + $row['price'];
							$total_land_pric= $total_land_pric +$row['land_price'];
							$total_house_price= $total_house_price +$row['house_price'];
							$property_type = $row['property_type'];
							?>
						<?php }?>
						<tr style=" border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;"><td colspan="11">&nbsp;</td></tr>
						<?php if(!empty($this->row)){?>
						<tr style="border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;"">
							<td colspan="12">
								<table border="1"​ style="border-collapse:collapse; border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
					                 <tr bgcolor="#c1d0f3" class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
					                 	<td>&nbsp;<?php echo $tr->translate("TOTAL_PROPERTY");?>&nbsp;</td>
					                 	<td>&nbsp;<?php echo $tr->translate("TOTAL_LAND_PRICE");?>&nbsp;</td>
					                 	<td>&nbsp;<?php echo $tr->translate("TOTAL_HOUSE_PRICE");?>&nbsp;</td>
					                 	<td>&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
					                 </tr>
					                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
					                  	<td align="center">&nbsp;<?php echo $i;?></td>
					                    <td>&nbsp;&nbsp;<?php echo number_format($total_land_pric,2);?>&nbsp;</td>
					                    <td>&nbsp;&nbsp;<?php echo number_format($total_house_price,2);?>&nbsp;</td>
					                    <td>&nbsp;&nbsp;<?php echo number_format($total,2);?>&nbsp;</td>
					                </tr>
					              </table>
							</td>
						</tr>
						<?php }?>
				    </table>
            	</td>
            </tr>
            </table>
			
    	</td>
    </tr>
</table>
</div>
