	<?php
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
		/*--------------------URLs link display--------------------------*/
		  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
		$arr_param_menu=array( 
			'home'=>array(
						'index'=>'<li><a href="">'.$tr->translate("HOME").'</a></li>',
			),
			'other'=>array(
						//'branch'=>'<li><a href="">'.$tr->translate("BRANCH_LIST").'</a></li>',
						'province'=>'<li><a href="">'.$tr->translate("PROVINCE").'</a></li>',
						'district'=>'<li><a href="">'.$tr->translate("DISTRICT").'</a></li>',
						'commune'=>'<li><a href="">'.$tr->translate("COMMUNE").'</a></li>',
						'village'=>'<li><a href="">'.$tr->translate("VILLAGE").'</a></li>',
						//'zone'=>'<li><a href="">'.$tr->translate("ZONE_AREA").'</a></li>',
						'holiday'=>'<li><a href="">'.$tr->translate("HOLIDAY_NAME").'</a></li>',
					   // 'callecteralltype'=>'<li><a href="">'.$tr->translate("COLLATERAL_TYPE").'</a></li>',
						'term'=>'<li><a href="">'.$tr->translate("TERMCONDICTION").'</a></li>' ,
						'loantype'=>'<li><a href="">'.$tr->translate("OTHER").'</a></li>' ,
			),
			'group'=>array(
					    'index'=>'<li><a href="">'.$tr->translate("CLIENT_INFO").'</a></li>',
					    'land'=>'<li><a href="">'.$tr->translate("PROPERTIES").'</a></li>',
						'propertiestype'=>'<li><a href="">'.$tr->translate("PROPERTY_TYPE").'</a></li>',
					    'project'=>'<li><a href="">'.$tr->translate("តារាងគំរោង").'</a></li>',
						'co'=>'<li><a href="">'.$tr->translate("Staff Name").'</a></li>',
						'position'=>'<li><a href="">'.$tr->translate("Staff Position").'</a></li>',
						//'changecollteral'=>'<li><a href="">'.$tr->translate("CHANGE_COLLETERAL").'</a></li>',
						//'returncollteral'=>'<li><a href="">'.$tr->translate("RETURN_COLLETERAL").'</a></li>',
						//'clientblacklist'=>'<li><a href="">'.$tr->translate("CLIENT_BLACKLIST").'</a></li>',
						//'callteral'=>'<li><a href="">'.$tr->translate("COLLETERAL").'</a></li>',
				),
			'loan'=>array(
						'index'=>'<li><a href="" title="">'.$tr->translate("IL_DISBURSE").'</a></li>',
						//'groupdisburse'=>'<li><a href="" title="">'.$tr->translate("GROUP_DISBURS").'</a></li>',
						'ilpayment'=>'<li><a href="" title="">'.$tr->translate("IL_PAYMENT").'</a></li>',
						'repaymentschedule'=>'<li><a href="" title="">'.$tr->translate("RESCHEDULE").'</a></li>',
						'income'=>'<li><a href="" title="">'.$tr->translate("INCOME").'</a></li>',
						'expense'=>'<li><a href="" title="">'.$tr->translate("EXPENSE").'</a></li>',
						'loantype'=>'<li><a href="">'.$tr->translate("ប្រភេទចំណូល /ចំណាយ").'</a></li>' ,
						'cancel'=>'<li><a href="">'.$tr->translate("CANCEL_SALE").'</a></li>' ,
						//'buyhouse'=>'<li><a href="" title="">'.$tr->translate("ទិញចូលវិញ").'</a></li>',
					    'transferproject'=>'<li><a href="" title="">'.$tr->translate("ផ្លាស់ប្តូគំរោង").'</a></li>',
				),
			'callecterall'=>array(
						'callecterall'=>'<li><a href="">'.$tr->translate("CALLECTERALL").'</a></li>',
						'callecteralllist'=>'<li><a href="">'.$tr->translate("CALLECTERALLLIST").'</a></li>',
						'chengcallecterall'=>'<li><a href="">'.$tr->translate("CHENGCALLECTERALL").'</a></li>',
						'refundcallecterall'=>'<li><a href="">'.$tr->translate("REFUNDCALLECTERALL").'</a></li>',
						'salecallecterall'=>'<li><a href="">'.$tr->translate("SALECALLECTERALL").'</a></li>',
							
				),
		   'payroll'=>array(
		   				'department'=>'<li><a href="">'.$tr->translate("DEPARTMENT").'</a></li>',
						'position'=>'<li><a href="">'.$tr->translate("POSITION").'</a></li>',
						'co'=>'<li><a href="">'.$tr->translate("STAFF").'</a></li>',
						'permission'=>'<li><a href="">'.$tr->translate("PERMISSION").'</a></li>',
		   				'salary'=>'<li><a href="">'.$tr->translate("SALARY").'</a></li>',
		   				//'setting'=>'<li><a href="">'.$tr->translate("SETTING").'</a></li>',
				),
			'tellerandexchange'=>array(
						//'teller'=>'<li><a href="">'.$tr->translate("កន្លែងបង់ប្រាក់").'</a></li>',
						'xchanges'=>'<li><a href="">'.$tr->translate("សេវាប្តូរប្រាក់").'</a></li>',
						//'xchange'=>'<li><a href="">'.$tr->translate("សេវាប្តូរប្រាក់").'</a></li>',
						'showrate'=>'<li><a href="">'.$tr->translate("ពិនិត្យអាត្រាប្តូរប្រាក់").'</a></li>',
						'spread'=>'<li><a href="">'.$tr->translate("កំណត់អាត្រាប្តូរប្រាក់").'</a></li>',
				),
				
			'capital'=>array(
						'capital'=>'<li><a href="">'.$tr->translate("BRANCH_CAPITAL").'</a></li>',
						'capital-transfer'=>'<li><a href="">'.$tr->translate("CAPITAL_TRANSFER").'</a></li>',
						'capital-resource'=>'<li><a href="">'.$tr->translate("CAPITAL_RESOURCE").'</a></li>',
		    ),
			'accounting'=>array(
					    'chartaccount'=>'<li><a href="">'.$tr->translate("តារាងនៃគណនី").'</a></li>',
					    /*'Accountcate'=>'<li><a href="">'.$tr->translate("ចំណែកថ្នាក់គណនី").'</a></li>',
						'Asset'=>'<li><a href="">'.$tr->translate("ទ្រព្យសកម្ម").'</a></li>',*/
						
						'expense'=>'<li><a href="">'.$tr->translate("ចំណាយផ្សេងៗ").'</a></li>',
						'income'=>'<li><a href="">'.$tr->translate("ចំណូលផ្សេងៗ").'</a></li>',
						'generaljurnal'=>'<li><a href="">'.$tr->translate("ទិនានុប្បវត្តិទូទៅ").'</a></li>',
						'adjustment'=>'<li><a href="">'.$tr->translate("កែតម្រូវទិនានុប្បវត្តិទូទៅ").'</a></li>',
						'ownerequity'=>'<li><a href="">'.$tr->translate("ទ្រព្យម្ចាស់").'</a></li>',
						'balancsheet'=>'<li><a href="">'.$tr->translate("សម្យតុល្យ").'</a></li>',
						'closingentry'=>'<li><a href="">'.$tr->translate("CLOSING").'</a></li>',
						'fixedasset'=>'<li><a href="">'.$tr->translate("រំលោះទ្រព្យសកម្ម").'</a></li>',
						'deposal'=>'<li><a href="">'.$tr->translate("លក់ទ្រព្យសកម្ម").'</a></li>',
				),
			'report'=>array(
						'paramater'=>'<li><a href="" title="">'.$tr->translate("PARAMATER").'</a></li>',
						'loan'=>'<li><a href="" title="">'.$tr->translate("LOAN_VIEW").'</a></li>',
				),
			'user'=>array(
				'index'=>'<li><a href="">'.$tr->translate("USER").'</a></li>',
			),	
			'rsvacl'=>array(
					 	//'index'=>'<li><a href="">'.$tr->translate("USER").'</a></li>',
					    'user'=>'<li><a href="">'.$tr->translate('USER').'</a></li>',
					    'acl'=>'<li><a href="">'.$tr->translate("ACL").'</a></li>',
						'useraccess'=>'<li><a href="">'.$tr->translate("USER_ACCESS").'</a></li>',
						'usertype'=>'<li><a href="">'.$tr->translate("USER_TYPE").'</a></li>',
				),
			'backup'=>array(
						'index'=>'<li><a href="">'.$tr->translate("Backup List").'</a></li>',
						'index'=>'<li><a href="">'.$tr->translate("Backup List").'</a></li>',
				),	
			'exchange'=>array(
						'index'=>'<li><a href="">'.$tr->translate("កន្លែងបង់ប្រាក់").'</a></li>',
						'exchange'=>'<li><a href="">'.$tr->translate("សេវាប្តូរប្រាក់").'</a></li>',
						'exchangerate'=>'<li><a href="">'.$tr->translate("កំណត់អាត្រាប្តូរប្រាក់").'</a></li>',
						'showrate'=>'<li><a href="">'.$tr->translate("ពិនិត្យអាត្រាប្តូរប្រាក់").'</a></li>',
				),
			'setting'=>array(
						'label'=>'<li><a href="">'.$tr->translate("Label_SETTING").'</a></li>',
						//'profile'=>'<li><a href="">'.$tr->translate("COM_PROFILE").'</a></li>',
						'database'=>'<li><a href="">'.$tr->translate("DATA_BASE_SETTING").'</a></li>',
						'setting'=>'<li><a href="">'.$tr->translate("System_SETTING").'</a></li>',
					
					)
				);       
	?>
	<div id="header-left">
	<ul>
			<?php 
if($request->getModuleName()!='default' AND $action!='changepassword' ){
				$dc=new Application_Model_Decorator();					
				$class="current-left";					
				$menu=$dc->getMenuLeft($arr_param_menu[$request->getModuleName()],$request->getControllerName(),$request->getModuleName());
				if($menu) echo $menu;	
}				
			?>
	</ul>																
	</div>
	<style>
	.current-left{  background: none repeat scroll 0 0 #EDF7F8 !important;}
	</style>